# Generated by Django 2.2 on 2019-04-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='text',
            field=models.TextField(default='<p>ERROR: TEXT MISSING</p>'),
        ),
    ]
