# Generated by Django 2.2 on 2019-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_subtopic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='topic',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
